platform:ios, '8.1'
target "WmjrApp" do
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'MMPopupView'
pod 'IQKeyboardManager'
pod 'SSKeychain'
pod 'Masonry'
pod 'DZNEmptyDataSet'
pod 'XHLaunchAd'
pod 'MBProgressHUD'
#pod 'KSCrash', '~> 1.8'
pod 'Bugly'
pod 'UMengAnalytics'
pod 'DZNEmptyDataSet'
pod 'ZLPhotoBrowser'
end

